cp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portal.urls')),
    path('accounts/', include('accounts.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.urls import path
from .views import *

app_name = 'portal'
urlpatterns = [
    path('', index_page, name='home_page'),
    path('members/', list_view_member, name='list_member_url'),
    path('attendances/', list_view_attendance, name='list_attendance_url'),
    path('att_summ/', attendance_summmaries_list, name='list_summary_attendance_url'),
    path('groups/', groups_list, name='list_group_url'),
    path('chapels/', chapel_list, name='list_chapel_url'),
    path('grouplead/', db_user_list, name='list_grouplead_url'),
    path('members/<int:pk>', members_details, name='details_member_urls'),
    path('groups/<int:pk>/', groups_details, name='details_group_urls'),
    path('chapels/<int:id>/', chapel_detail, name='details_chapels_urls'),
    # path('grouplead/<int:pk>/', db_user_details, name='details_grouplead_urls'),
    # # path('members/<id>/', details_membs, name='details_members_urls'),
    path('addgroup/', create_view_group, name='add_group_url'),
    path('addchapel/', create_chapel, name='add_chapel_url'),
    path('memlist/', memberindex, name='lazyloadmem'),
    # # path('dbuserlistindex/', db_userindex, name='mems'),
    # path('groups/<int:pk>/delete', group_delete, name='delete_group'),
    # path('groups/<int:pk>/delete', dbuser_delete, name='delete_group_head'),
    path('add_member/', create_members, name='add_member_url'),
    path('add_dbuser/', create_pcheads, name='add_dbuser_url'),
    path('abs/', list_atbsentee, name='absent_url'),

]

templates/member/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CTAC | New Member{% endblock %}
{% block content %}
  <div class="content-wrapper">
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
          </div>
        </div>
      </div>
    </section>
    <section class="content">
      <div class="row">
        <div class="col-md-6">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">ADD Member </h3>
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fas fa-minus"></i></button>
              </div>
            </div>
            <div class="card-body">
              <div class="form-group">
                <form method="POST" action="">
                  {% csrf_token %}
                    <div class="form-group">
                    <label>Title </label>
                    <input
                      type='text'
                      name='title'
                      class="form-control"
                      placeholder="Mr. Mrs. Rev. ">
                  </div>
                  <div class="form-group">
                    <label>Last Name </label>
                    <input
                      type='text'
                      name='last_name'
                      class="form-control"
                      placeholder="Enter last name">
                  </div>
                    <div class="form-group">
                    <label>First Name </label>
                    <input
                      type='text'
                      name='first_name'
                      class="form-control"
                      placeholder="Enter first name">
                  </div>
                    <div class="form-group">
                    <label>Other Name </label>
                    <input
                      type='text'
                      name='other_name'
                      class="form-control"
                      placeholder="Enter Other name">
                  </div>
                    <div class="form-group">
                    <label>Gender </label>
                    <input
                      type='text'
                      name='sex'
                      class="form-control"
                      placeholder="Male or Female">
                  </div>
                    <div class="form-group">
                    <label>Phone Number </label>
                    <input
                      type='tel'
                      name='phone_number'
                      class="form-control"
                      placeholder="0547232768">
                  </div>
                    <div class="form-group">
                    <label>Whatsapp Phone </label>
                    <input
                      type='tel'
                      name='whatsapp_number'
                      class="form-control"
                      placeholder="0547232768">
                  </div>
                    <div class="form-group">
                    <label>Other Phone </label>
                    <input
                      type='tel'
                      name='other_phone_number'
                      class="form-control"
                      placeholder="0547232768">
                  </div>
                     <div class="form-group">
                    <label>Area of Residence </label>
                    <input
                      type='text'
                      name='area_of_residence'
                      class="form-control"
                      placeholder="Nungua">
                  </div>
                     <div class="form-group">
                    <label>GPS Address </label>
                    <input
                      type='tel'
                      name='gps_address'
                      class="form-control"
                      placeholder="GA-000-0000">
                  </div>
                     <div class="form-group">
                    <label>DOB </label>
                    <input
                      type='date'
                      name='dob'
                      class="form-control"
                      placeholder="21/02/2000">
                  </div>
                    <div class="form-group">
                         <label>Select PC Group</label><br>
                    {{ mem_create.group }}<br>
                        &nbsp;<br>
                         <label>Select Chapel</label><br>
                    {{ mem_create.chapel }}
                    </div>



                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

{% endblock %}

templates/member/details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CTAC | {{ mem_det.last_name|capfirst }} {{ mem_det.other_name|default_if_none:"" }}{{ mem_det.first_name|capfirst }}{% endblock %}
{% block content %}

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1> {{ mem_det.first_name|capfirst }}&nbsp;{{ mem_det.other_name|default_if_none:"" }}&nbsp;{{ mem_det.last_name|capfirst }}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{% url 'portal:home_page' %}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'portal:list_member_url' %}">Members</a></li>
                            <li class="breadcrumb-item active">{{ mem_det.first_name|capfirst  }}&nbsp;{{ mem_det.other_name|default_if_none:"" }}&nbsp;{{ mem_det.last_name|capfirst }}</li>
                        </ol>
                    </div>
                </div>
            </div>

        </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6">

            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle"
                       src="{% static 'dist/img/user4-128x128.jpg' %}"
                       alt="User profile picture">
                </div>

                <h4 class="profile-username text-center">{{ mem_det.first_name|capfirst}} {{ mem_det.other_name |default_if_none:"" |capfirst  }} {{ mem_det.last_name|capfirst }}</h4>

                  <a href="{% url 'portal:details_group_urls' mem_det.group.id%}" class="btn btn-default btn-block btn-flat">{{ mem_det.group }}</a>

                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item">
                    <b>Title</b> <p class="float-right" class="text-black">{{ mem_det.title|capfirst |default_if_none:""}}</p>
                  </li>
                  <li class="list-group-item">
                    <b>Gender</b> <p class="float-right" class="text-black">{{ mem_det.sex |capfirst|default_if_none:""}}</p>
                  </li>
                  <li class="list-group-item">
                    <b>Date of Birth</b> <p class="float-right" class="text-black">{{ mem_det.dob  }}</p>
                  </li>
                </ul>

                <a href="{% url 'portal:details_chapels_urls' mem_det.chapel.id%}" class="btn btn-primary btn-block"><b>{{ mem_det.chapel }}</b></a>
              </div>

            </div>

          </div>
          <div class="col-md-6">
            <div class="card">


              <div class="card-header">
                <h3 class="card-title">Residents & Contact</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <i class="fas fa-lg fa-building"></i> GPS Address

                <p class="text-black">
                  {{ mem_det.gps_address |default_if_none:""|capfirst}}
                </p>

                <hr>

                <i class="fas fa-map-marker-alt mr-1"></i> House Address

                &nbsp;<p class="text-black"> &nbsp;{{ mem_det.area_of_residence |default_if_none:""|capfirst}}</p>

                <hr>

              &nbsp; <i class="fas fa-lg fa-phone"></i> &nbsp;Phone

                <p class="text-black">
                  <span class="tag tag-danger">{{ mem_det.phone_number}}</span><br>
                  <span class="tag tag-success">{{ mem_det.whatsapp_number|default_if_none:""}}</span>
                  <span class="tag tag-info">{{ mem_det.other_phone_number|default_if_none:"" }}</span><br>
                </p>
              </div>
            </div>
            </div>
          </div>
        </div>
    </section>
      </div>
    </section>
    </div>


    <div class="modal fade" id="modal-default">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Default Modal</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <section class="content">
                  <div class="container-fluid">
                    <div class="row">
                      <div class="col-md-6">
            
                        <!-- Profile Image -->
                        <div class="card card-primary card-outline">
                          <div class="card-body box-profile">
                            <div class="text-center">
                              <img class="profile-user-img img-fluid img-circle"
                                   src="{% static 'dist/img/user4-128x128.jpg' %}"
                                   alt="User profile picture">
                            </div>

                            <h4 class="profile-username text-center">{{ mem_det.first_name|capfirst}} {{ mem_det.other_name|capfirst |default_if_none:""  }} {{ mem_det.last_name|capfirst }}</h4>
            
                              <a href="{% url 'portal:details_group_urls' mem_det.group.id%}" class="btn btn-default btn-block btn-flat">{{ mem_det.group }}</a>
            
                            <ul class="list-group list-group-unbordered mb-3">
                              <li class="list-group-item">
                                <b>Title</b> <p class="float-right" class="text-black">{{ mem_det.title|capfirst |default_if_none:""}}</p>
                              </li>

                              <li class="list-group-item">
                                <b>Gender</b> <p class="float-right" class="text-black">{{ mem_det.sex |capfirst|default_if_none:""}}</p>
                              </li>
                              <li class="list-group-item">
                                <b>Date of Birth</b> <p class="float-right" class="text-black">{{ mem_det.dob|date:"d M, Y"  }}</p>
                              </li>
                            </ul>
            
                            <a href="{% url 'portal:details_chapels_urls' mem_det.chapel.id%}" class="btn btn-primary btn-block"><b>{{ mem_det.chapel }}</b></a>
                          </div>
            
                        </div>
            
                      </div>
                      <div class="col-md-6">
                        <div class="card">
            
            
                          <div class="card-header">
                            <h3 class="card-title">Residents & Contact</h3>
                          </div>
                          <!-- /.card-header -->
                          <div class="card-body">
                            <i class="fas fa-lg fa-building"></i> GPS Address
            
                            <p class="text-black">
                              {{ mem_det.gps_address |default_if_none:""}}
                            </p>
            
                            <hr>
            
                            <i class="fas fa-map-marker-alt mr-1"></i> House Address
            
                            &nbsp;<p class="text-black"> &nbsp;{{ mem_det.area_of_residence |default_if_none:""}}</p>
            
                            <hr>
            
                          &nbsp; <i class="fas fa-lg fa-phone"></i> &nbsp;Phone
            
                            <p class="text-black">
                              <span class="tag tag-danger">{{ mem_det.phone_number}}</span><br>
                              <span class="tag tag-success">{{ mem_det.whatsapp_number|default_if_none:""}}</span>
                              <span class="tag tag-info">{{ mem_det.other_phone_number|default_if_none:"" }}</span><br>
                            </p>
                          </div>
                        </div>
                        </div>
                      </div>
                    </div>
                </section>
          </div>
          <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
        <!-- /.modal-content -->
      </div>
      <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->

{% endblock %}

templates/member/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CTAC | Members{% endblock %}
{% block content %}

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2 row-heading">
                    <div class="col-sm-6">
                        <h1 class="pc-heading">PC Members</h1>
                    </div>
                    <a href="{% url 'portal:add_member_url' %}"
                                           class="btn btn-sm btn-info float-left btn-add-mem">Add Member</a>
                </div>
                <div class="card card-body">
                    <form method="get">
{{ myFilter.form }}
                        <button type="submit" class="btn btn-sm btn-info float-right btn-add-mem-"> Filter</button>
                    </form>
                </div>

            </div>
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
{#                        <div class="card">#}
                            <div class="card">
                                <div class="card-body">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead class="table-tr-color">
                                        <tr>
                                            <th>ID</th>
                                            <th> NAME</th>
                                            <th>PHONE NUMBER</th>
                                            <th> CHAPEL NAME</th>
                                            <th> PC GROUP</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for memlist in memlist %}
                                            <tr>
                                                <td>{{ memlist.id }}</td>
                                                 <td><a href="{% url 'portal:details_member_urls' memlist.id %}"
                                                   class="link-black">{{ memlist.first_name|capfirst }}&nbsp;{{ memlist.last_name|capfirst }}</a></td>
{#                                               <td> <a>< href="{% url 'portal:details_member_urls' memlist.id%}{{ memlist.last_name }}</a></td>#}
                                                <td>{{ memlist.phone_number }}</td>
                                                <td>{{ memlist.chapel|capfirst }}</td>
                                                <td>{{ memlist.group }}</td>
                                            </tr>
                                        {% endfor %}


                                    </table>
                                    <div class="card-footer clearfix">
                                        <a href="{% url 'portal:add_member_url' %}"
                                           class="btn btn-sm btn-info btn-add-mem float-left">Add Member</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </section>
            </div>
{% endblock %}