accounts/urls.py
from django.urls import path
from .views import register, login, logout, activate, forgetpassword, resetpassword, resetpasswordValiate

app_name = 'accounts'

urlpatterns = [
    path('signup/', register, name='signup_url'),
    path('login/', login, name='login_url'),
    path('logout/', logout, name='sign_out_url'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),

    # Password Mgmt
    path('forgotpassword/', forgetpassword, name='forgotpassword_url'),
    path('resetpassword/', resetpassword, name='resetpassword_url'),
    path('resetpasswordv/<uidb64>/<token>/', resetpasswordValiate, name='reset_password_validate_url'),


]

cp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portal.urls')),
    path('accounts/', include('accounts.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


# Create your models here.
# User accounts Manager
class MyAccountManager(BaseUserManager):
    def create_user(self, last_name, username, email, phone, password=None):
        if not email:
            raise ValueError('User must have an email address')
        if not username:
            raise ValueError("User must have a username")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            # first_name=first_name,
            last_name=last_name,
            phone=phone,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, last_name, email, username, phone, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            # first_name=first_name,
            last_name=last_name,
            phone=phone

        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=20, unique=True)
    email = models.EmailField(max_length=50, unique=True)
    phone = models.CharField(max_length=50)
    # required Fields
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    # I set to False to so i can verified the mail of the user ie is_active is always True when am not verifing a user
    is_active = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    # login
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'last_name', 'phone']
    #  u will always need to end the class with() or natural key error awaits
    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True


class UserProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    profile_pic = models.FileField(upload_to='user_profile/%Y/%m/%d/', blank=True)

    def __str__(self):
        return self.user.last_name

accounts/forms.py
from django import forms
from .models import Account, UserProfile


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'form-control',

    }))
    passwordconfirm = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }))

    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'email', 'phone', 'password']

    def _init_(self, *args, **kwargs):
        super(RegistrationForm, self)._init_(args, *kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter first Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Last Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Emaill Address'
        self.fields['phone'].widget.attrs['placeholder'] = 'Enter Your phone Number'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        passwordconfirm = cleaned_data.get('passwordconfirm')

        if password != passwordconfirm:
            raise forms.ValidationError('Passwords dont Match')

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        passwordconfirm = cleaned_data.get('passwordconfirm')

        if password != passwordconfirm:
            raise forms.ValidationError('Passwords dont Match')


# user Form for editing and updating
class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'phone')

    def _init_(self, *args, **kwargs):
        super(UserForm, self)._init_(args, *kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)

    def _init_(self, *args, **kwargs):
        super(UserProfileForm, self)._init_(args, *kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

accounts/views.py
from django.contrib import messages, auth
from django.shortcuts import render, redirect, get_object_or_404
from .models import Account
from .forms import RegistrationForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate


# Create your views here.
@login_required(login_url='accounts:login_url')
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']

            password = form.cleaned_data['password']
            username = email.split("@")[0]
            user = Account.objects.create_user(last_name=last_name,
                                               phone=phone, email=email,
                                               username=username, password=password)
            user.save()
            current_site = get_current_site(request)
            mail_subject = "Accounts Activation"
            message = render_to_string('accounts/verification.html', {
                'user': user,
                'domian': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })

            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()
            messages.success(request, 'Sign up was successful, please complete your verification from your mail')
            return redirect('/accounts/login/?command=verification&email=' + email)
    else:
        form = RegistrationForm()
        context = {
            'form': form,
        }
        return render(request, 'accounts/signup.html', context)


# def login(request):
#     if request.method == 'POST':
#         email = request.POST['email']
#         password = request.POST['password']
#
#         user = auth.authenticate(email=email, password=password)
#         if user is not None:
#             auth.login(request, user)
#             return redirect('portal:home_page')
#         else:
#             messages.error(request, "Invalid Credentials")
#             return redirect('accounts:login_url')
#
#     return render(request, 'accounts/login.html')


def login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, email=email, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('portal:home_page')

    return render(request, 'accounts/login.html')


@login_required(login_url='accounts:login_url')
def logout(request):
    auth.logout(request)
    messages.success(request, "You're logged out")
    return redirect('accounts:login_url')


@login_required(login_url='accounts:login_url')
def activate(request, uidb64, token):
    user = get_object_or_404(Account, pk=urlsafe_base64_decode(uidb64).decode())
    if default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Congratulations! Your account is activated.')
        return redirect('accounts:login_url')
    else:
        messages.error(request, "Invalid activation link.")
        return redirect('register')
    # return HttpResponse('ok')


#
#
#
def forgetpassword(request):
    if request.method == 'POST':
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)

            current_site = get_current_site(request)
            mail_subject = "Accounts Reset"
            message = render_to_string('accounts/reset_verification.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })

            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(request, "password reset email has been sent to your mail")
            return redirect('accounts:login_url')

        else:
            messages.error(request, 'Accounts Doesnot Exist')
            return redirect('accounts:forgotpassword_url')

    return render(request, 'accounts/forgetpasswords.html')


def resetpasswordValiate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesnotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, 'Please Reset Your Password')
        return redirect('accounts:resetpassword_url')

    else:
        messages.error(request, 'This link is expired')
        return redirect('accounts:login_url')


def resetpassword(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password Reset Was Successful')
            return redirect('accounts:login_url')
        else:
            messages.error(request, "passwords dont match")
            return redirect('accounts:resetpassword_url')
    else:
        return render(request, 'accounts/passreset.html')

templates/accounts/forgetpasswords.html
{% block  content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>CTAC |Forgot password </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" href="{% static 'images/icons/ctaclogo.png' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/loginutil.css' %}">
	<link rel="stylesheet" type="text/css" href="{%  static 'css/loginmain.css' %}">
</head>
<body>

	<div class="limiter">
		<div class="container-login100"  style="background-image: url({% static 'images/bg.jpg' %}); ">

			<div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
              {% include 'alerts.html' %}
				<form action="{% url 'accounts:forgotpassword_url' %}" method="POST"  class="login100-form validate-form flex-sb flex-w">
                    {% csrf_token %}

                    <span class="login100-form-title p-b-53">
						Forgot Password
					</span>


					<div class="p-t-31 p-b-9">
						<span class="txt1">
							Email
						</span>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Email Address is required">
						<input class="input100" type="email" name="email" >
						<span class="focus-input100"></span>
					</div>

{#					<div class="p-t-13 p-b-9">#}
{#						<span class="txt1">#}
{#							Password#}
{#						</span>#}

{#						<a href="{% url 'accounts:resetpassword_validate_url' %}" class="txt2 bo1 m-l-5">#}
{#							Forgot?#}
{#						</a>#}
{#					</div>#}
{#					<div class="wrap-input100 validate-input" data-validate = "Password is required">#}
{#						<input class="input100" type="password" name="password" >#}
{#						<span class="focus-input100"></span>#}
{#					</div>#}

					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn">
							Send
						</button>
					</div>

					<div class="w-full text-center p-t-55">
						<span class="txt2">
							 with an account?
						</span>

						<a href="{% url 'accounts:login_url' %}" class="txt   2 bo1">
							Sign In now
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.j' %}s"></script>
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>
{% endblock %}

templates/accounts/forgotpassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/accounts/login.html
{% block  content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Ctac  | Login </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" href="{% static 'images/icons/ff.ico' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/loginutil.css' %}">
	<link rel="stylesheet" type="text/css" href="{%  static 'css/loginmain.css' %}">
</head>
<body>

	<div class="limiter">
		<div class="container-login100"  style="background-image: url({% static 'images/bg.jpg' %}); ">

			<div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
              {% include 'alerts.html' %}
				<form action="{% url 'accounts:login_url' %}" method="POST"  class="login100-form validate-form flex-sb flex-w">
                    {% csrf_token %}
					{% if request.GET.next %}
                                 <input type="hidden" name="next" value="{{request.GET.next }}">
                               {% endif %}
                    <span class="login100-form-title p-b-53">
						Sign In
					</span>


					<div class="p-t-31 p-b-9">
						<span class="txt1">
							Email
						</span>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Email Address is required">
						<input class="input100" type="email" name="email" >
						<span class="focus-input100"></span>
					</div>

					<div class="p-t-13 p-b-9">
						<span class="txt1">
							Password
						</span>

						<a href="#" class="txt2 bo1 m-l-5">
							Forgot?
						</a>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" >
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn">
							Sign In
						</button>
					</div>

{#					<div class="w-full text-center p-t-55">#}
{#						<span class="txt2">#}
{#							Not with an account?#}
{#						</span>#}
{##}
{#						<a href="{% url 'accounts:signup_url' %}" class="txt2 bo1">#}
{#							Sign up now#}
{#						</a>#}
{#					</div>#}
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.j' %}s"></script>
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>
{% endblock %}

templates/accounts/passreset.html
{% block  content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>CTAC  | Change Password </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" href="{% static 'images/icons/ctaclog.png' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/loginutil.css' %}">
	<link rel="stylesheet" type="text/css" href="{%  static 'css/loginmain.css' %}">
</head>
<body>

	<div class="limiter">
		<div class="container-login100"  style="background-image: url({% static 'images/bg.jpg' %}); ">

			<div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
              {% include 'alerts.html' %}
				<form action="{% url 'accounts:resetpassword_url' %}" method="POST"  class="login100-form validate-form flex-sb flex-w">
                    {% csrf_token %}

                    <span class="login100-form-title p-b-53">
						Reset Password
					</span>


					<div class="p-t-31 p-b-9">
						<span class="txt1">
							Password
						</span>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "password is required">
						<input class="input100" placeholder="Enter password" type="password" name="password" >
						<span class="focus-input100"></span>
					</div>

					<div class="p-t-13 p-b-9">
						<span class="txt1">
							 Confirm Password
						</span>

					</div>
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" placeholder="Confirm Password" type="password" name="confirm_password" >
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn">
							Reset Password
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.j' %}s"></script>
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>
{% endblock %}

templates/accounts/reset_verification.html
{% autoescape off %}
Hi {{ user.first_name }},
    Please reset your password with the link below.
    http://{{ domain }}{% url  'accounts:reset_password_validate_url' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/resetpassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/accounts/signup.html
{% load static %}
{% block  content %}
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>CTAC Portal | Sign up </title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="{% static 'images/icons/ff.ico' %}"/>
        <link href="{% static 'signup/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet"
              media="all">
        <link href="{% static 'signup/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet"
              media="all">
        <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
              rel="stylesheet">
        <link href="{% static 'signup/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
        <link href="{% static 'signup/vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">
        <link href="{% static 'signup/css/main.css' %}" rel="stylesheet" media="all">
    </head>

    <body>
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <h2 class="title">Signup </h2>
                    {% include 'alerts.html' %}
                    <form action="{% url 'accounts:signup_url' %}" method="POST">
                        {% csrf_token %}
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">first name</label>
                                    <input class="input--style-4" type="text" name="first_name" required>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">last name</label>
                                    <input class="input--style-4" type="text" name="last_name" required>
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Email</label>
                                    <input class="input--style-4" type="email" name="email" required>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Phone Number</label>
                                    <input class="input--style-4" type="text" name="phone">
                                </div>
                            </div>
                        </div>

                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Password</label>
                                    <input class="input--style-4" type="password" name="password" required
                                           pattern="{8,15}$">
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Confirm Password</label>
                                    <input class="input--style-4" type="password" name="passwordconfirm">
                                </div>
                            </div>
                        </div>

                        <div class="p-t-15">
                            <button class="btn btn--radius-2 btn--blue" type="submit">Submit</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'signup/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'signup/vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'signup/vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'signup/vendor/datepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'signup/js/global.js' %}"></script>
    </body>
    </html>

{% endblock %}

templates/accounts/userdashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/accounts/verification.html
{% autoescape off %}
Hi {{ user.last_name }},
    Please confirm your registration.
    http:///{{ domian }}{% url  'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}