cp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portal.urls')),
    path('accounts/', include('accounts.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.urls import path
from .views import *

app_name = 'portal'
urlpatterns = [
    path('', index_page, name='home_page'),
    path('members/', list_view_member, name='list_member_url'),
    path('attendances/', list_view_attendance, name='list_attendance_url'),
    path('att_summ/', attendance_summmaries_list, name='list_summary_attendance_url'),
    path('groups/', groups_list, name='list_group_url'),
    path('chapels/', chapel_list, name='list_chapel_url'),
    path('grouplead/', db_user_list, name='list_grouplead_url'),
    path('members/<int:pk>', members_details, name='details_member_urls'),
    path('groups/<int:pk>/', groups_details, name='details_group_urls'),
    path('chapels/<int:id>/', chapel_detail, name='details_chapels_urls'),
    # path('grouplead/<int:pk>/', db_user_details, name='details_grouplead_urls'),
    # # path('members/<id>/', details_membs, name='details_members_urls'),
    path('addgroup/', create_view_group, name='add_group_url'),
    path('addchapel/', create_chapel, name='add_chapel_url'),
    path('memlist/', memberindex, name='lazyloadmem'),
    # # path('dbuserlistindex/', db_userindex, name='mems'),
    # path('groups/<int:pk>/delete', group_delete, name='delete_group'),
    # path('groups/<int:pk>/delete', dbuser_delete, name='delete_group_head'),
    path('add_member/', create_members, name='add_member_url'),
    path('add_dbuser/', create_pcheads, name='add_dbuser_url'),
    path('abs/', list_atbsentee, name='absent_url'),

]

templates/chapels/add.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CTAC | Add Chapel{% endblock %}
{% block content %}
  <div class="content-wrapper">
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
          </div>
        </div>
      </div>
    </section>
    <section class="content">
      <div class="row">
        <div class="col-md-6">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">ADD CHAPEL </h3>
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fas fa-minus"></i></button>
              </div>
            </div>
            <div class="card-body">
              <div class="form-group">
                <form method="POST" action="">
                  {% csrf_token %}
                  <div class="form-group">
                    <label>Chapel Name </label>
                    <input
                      type='text'
                      name='name'
                      class="form-control"
                      placeholder="Enter chapel name">
                  </div>

                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

{% endblock %}

templates/chapels/details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CTAC | {{ chapdetails.name }}{% endblock %}
{% block content %}

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1> {{ chapdetails.name }}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{% url 'portal:home_page' %}">Home</a></li>
                            <li class="breadcrumb-item"><a
                                    href="{% url 'portal:list_chapel_url' %}">Chapels</a></li>
                            <li class="breadcrumb-item active">{{ chapdetails.name }}</li>
                        </ol>
                    </div>
                </div>

            </div>
        </section>
        <div class="card-body">
            <div class="row">
                <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
                    <div class="row">
                        <div class="col-12 col-sm-4">
                            <div class="info-box bg-light">
                                <div class="info-box-content">
                                    <span class="info-box-text text-center text-muted">{{ chapdetails.name }} &nbsp; Total Group Heads</span>
                                    <span class="info-box-number text-center text-muted mb-0">{{ dbuser_count }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-sm-4">
                            <div class="info-box bg-light">
                                <div class="info-box-content">
                                    <span class="info-box-text text-center text-muted">{{ chapdetails.name }} Total Members </span>
                                    <span class="info-box-number text-center text-muted mb-0">{{ ch_mem_count }} </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card">
                                <div class="card-body">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                        <tr>
                                            <th>Last name</th>
                                            <th> Other name</th>
                                            <th>First name</th>
                                            <th> Group name</th>
                                            <th>Phone number</th>
{#                                            <th>chapel</th>#}

                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for cha_mem in cha_mem %}
                                            <tr>
                                                <td>{{ cha_mem.last_name }}</td>
                                                <td> {{ cha_mem.other_name|default_if_none:"" }}</td>
                                                <td>{{ cha_mem.first_name }}</td>
                                                 <td>{{ cha_mem.group.name }}</td>
                                                  <td>{{ cha_mem.phone_number }}</td>
{#                                                  <td>{{ cha_mem.chapel }}</td>#}

                                            </tr>
                                        {% endfor %}

                                        </tfoot>
                                    </table>
                                &nbsp;
                                    <div class="card">
                                        <div class="card-header border-transparent">
                                            <h3 class="card-title">Leaders of {{ chapdetails.name }} Chapel</h3>
                                            <div class="card-body p-0">
                                                <div class="table-responsive">
                                                    <table class="table m-0">
                                                        <thead>
                                                        <tr>
                                                            <th>ID</th>
                                                            <th>Name</th>
                                                            <th>Email</th>
                                                            <th> Group</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                       {% for db_users in db_users %}
                                            <tr>
                                                <td>{{ db_users.id }}</td>
                                                <td> {{ db_users.name }}</td>
                                                <td>{{ db_users.email }}</td>
                                               <td>{{ db_users.group.name }}</td>

                                            </tr>
                                        {% endfor %}

                                                        </tbody>
                                                    </table>
                                                </div>
                                                <!-- /.table-responsive -->
                                            </div>
                                            <!-- /.card-body -->
{#                                            <div class="card-footer clearfix">#}
{#                                                <a href="javascript:void(0)" class="btn btn-sm btn-info float-left">Place#}
{#                                                    New Order</a>#}
{#                                                <a href="javascript:void(0)"#}
{#                                                   class="btn btn-sm btn-secondary float-right">View All Orders</a>#}
{#                                            </div>#}
                                            <!-- /.card-footer -->
                                        </div>
                                        <!-- /.card -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>
{% endblock %}

templates/chapels/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CTAC | CHAPELS {% endblock %}
{% block content %}
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Chapels</h1>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
{#                            <div class="card">#}
                                <div class="card-body">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th> CHAPEL</th>
                                            <th>DATE ADDED</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for chaps in chaps %}
                                            <tr>
                                                <td>{{ chaps.id }}</td>
                                                <td><a href="{% url 'portal:details_chapels_urls' chaps.id %}"
                                                       class="link-black">{{ chaps.name }}</a></td>
                                                <td>{{ chaps.created_at| date:"d M, Y" }}</td>

                                            </tr>
                                        {% endfor %}

                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <div class="card-footer clearfix">
                                <a href="{% url 'portal:add_chapel_url' %}"
                                   class="btn btn-sm btn-add-chapel float-right">New Chapel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    </section>
    </div>

    </div>
{% endblock %}