accounts/urls.py
from django.urls import path
from .views import register, login, logout, activate, forgetpassword, resetpassword, resetpasswordValiate

app_name = 'accounts'

urlpatterns = [
    path('signup/', register, name='signup_url'),
    path('login/', login, name='login_url'),
    path('logout/', logout, name='sign_out_url'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),

    # Password Mgmt
    path('forgotpassword/', forgetpassword, name='forgotpassword_url'),
    path('resetpassword/', resetpassword, name='resetpassword_url'),
    path('resetpasswordv/<uidb64>/<token>/', resetpasswordValiate, name='reset_password_validate_url'),


]

cp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portal.urls')),
    path('accounts/', include('accounts.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.urls import path
from .views import *

app_name = 'portal'
urlpatterns = [
    path('', index_page, name='home_page'),
    path('members/', list_view_member, name='list_member_url'),
    path('attendances/', list_view_attendance, name='list_attendance_url'),
    path('att_summ/', attendance_summmaries_list, name='list_summary_attendance_url'),
    path('groups/', groups_list, name='list_group_url'),
    path('chapels/', chapel_list, name='list_chapel_url'),
    path('grouplead/', db_user_list, name='list_grouplead_url'),
    path('members/<int:pk>', members_details, name='details_member_urls'),
    path('groups/<int:pk>/', groups_details, name='details_group_urls'),
    path('chapels/<int:id>/', chapel_detail, name='details_chapels_urls'),
    # path('grouplead/<int:pk>/', db_user_details, name='details_grouplead_urls'),
    # # path('members/<id>/', details_membs, name='details_members_urls'),
    path('addgroup/', create_view_group, name='add_group_url'),
    path('addchapel/', create_chapel, name='add_chapel_url'),
    path('memlist/', memberindex, name='lazyloadmem'),
    # # path('dbuserlistindex/', db_userindex, name='mems'),
    # path('groups/<int:pk>/delete', group_delete, name='delete_group'),
    # path('groups/<int:pk>/delete', dbuser_delete, name='delete_group_head'),
    path('add_member/', create_members, name='add_member_url'),
    path('add_dbuser/', create_pcheads, name='add_dbuser_url'),
    path('abs/', list_atbsentee, name='absent_url'),

]

templates/alerts.html
{%  if  messages %}
    <ul class="messages">
    {%  for message in messages %}
        <div id="message" class=""container>
        <div {% if message.tags %} class ="alert alert-{{ message.tags }}"{% endif %} role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true"></span> </button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} Important: {% endif %}
        {{ message }}
        </div>

        </div>
    {% endfor %}
    </ul>
{% endif %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{{ section.title }}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'dist/img/ctaclogo.png' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/dropzone/min/dropzone.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static '/customCSS/styles.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.0/dist/chart.umd.min.js"></script>
</head>

<style>
    a:hover {
        background-color: transparent;
    }
</style>
<body class="hold-transition sidebar-mini layout-fixed  layout-navbar-fixed  layout-footer-fixed">
<div class="wrapper">

    <div class="wrapper">
        <nav class="main-header navbar navbar-expand navbar-dark ">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'portal:home_page' %}" class="nav-link hori-nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">

                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                        <i class="fas fa-search"></i>
                    </a>
                    <div class="navbar-search-block">
                        <form class="form-inline">
                            <div class="input-group input-group-sm">
                                <input class="form-control form-control-navbar" type="search" placeholder="Search"
                                       aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-navbar" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                    <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>
            </ul>
        </nav>

        <aside class="main-sidebar sidebar-light-primary elevation-4">
            <a href="{% url 'portal:home_page' %}" class="brand-link">

                <span class="brand-text font-weight-light">{{ request.user.first_name }}&nbsp;{{ request.user.last_name }}</span>
            </a>`
            <div class="sidebar">
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <li class="nav-item">
                            <a href="{% url 'portal:list_member_url' %}" class="nav-link">
                                <i class="fas fa-users"></i> &nbsp;

                                <p>
                                    Members

                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'portal:list_group_url' %}" class="nav-link">
                                <i class="ion ion-stats-bars"></i> &nbsp;
                                <p>
                                    PC Groups
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'portal:list_grouplead_url' %}" class="nav-link">
                                <i class="ion ion-person"></i> &nbsp;
                                <p>
                                    Group Heads
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'portal:list_chapel_url' %}" class="nav-link">
                                <i class="far fa-building"></i> &nbsp;
                                <p>
                                    Chapel
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'portal:list_attendance_url' %}" class="nav-link">
                                <i class="far fa-file-alt mr-1"></i> &nbsp;
                                <p>
                                    Present
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'portal:absent_url' %}" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i> &nbsp;
                                <p>
                                    Absent
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'portal:list_summary_attendance_url' %}" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i> &nbsp;
                                <p>
                                    Attendances Summary
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'accounts:sign_out_url' %}" class="nav-link">
                                <i class="fas fa-door-closed"></i> &nbsp;
                                <p>
                                    Logout
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'accounts:signup_url' %}" class="nav-link">
                                <i class="fas fa-user-plus"></i>&nbsp;
                                <p>
                                    New User
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
    </div>

    {% block content %}

    {% endblock %}
    <div id="modal" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
        </div>
    </div>

    <footer class="main-footer">
        <b>PastCare</b> &nbsp;
        <a href="https://github.com/FiifiQwontwo" target="_blank">Powered By Fortem
        </a>
        <div class="float-right d-none d-sm-inline-block">
            <strong>Copyright &copy; 2014-{% now 'Y' %} .</strong>
        </div>
    </footer>

    <aside class="control-sidebar control-sidebar-dark">
    </aside>

</div>

<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<script> $.widget.bridge('uibutton', $.ui.button)</script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<script src="{% static 'dist/js/adminlte.js' %}"></script>
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/dropzone/min/dropzone.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
{#<script src="https://unpkg.com/htmx.org@1.7.0"></script>#}
<script src="https://unpkg.com/htmx.org@1.6.1"></script>
<script src="{% static 'dialog.js' %}"></script>
<script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true, "lengthChange": false, "autoWidth": false,
            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    });

    function launchModal() {
        $('#modal-default').modal()
    }
</script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CTAC | Dashboard{% endblock %}
{% block content %}
    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">

            </div>
        </div>
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>{{ memcounts }}</h3>
                                <a href="{% url 'portal:list_member_url' %}" class="nav-link">
                                    <h6 style="color: #070707">Members</h6></a>
                            </div>
                            <div class="icon">

                                <i class="fas fa-users"></i>

                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-success">
                            <div class="inner">
                                <h3>{{ groupcount }}</h3>
                                <a href="{% url 'portal:list_group_url' %}" class="nav-link">
                                    <h6 style="color: #070707">PC Groups</h6></a>
                            </div>
                            <div class="icon">
                                <i class="ion ion-stats-bars"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-gradient-red">
                            <div class="inner">
                                <h3>{{ usercount }}</h3>
                                <a href="{% url 'portal:list_grouplead_url' %}" class="nav-link">
                                    <h6 style="color: #070707"> PC Group Heads</h6></a>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-gradient-secondary">
                            <div class="inner">
                                <h3>{{ chapscount }}</h3>
                                <a href="{% url 'portal:list_chapel_url' %}" class="nav-link">
                                    <h6 style="color: #070707">Chapels</h6></a>
                            </div>
                            <div class="icon">
                                <i class="far fa-building"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Pastorial Group Heads</h3></div>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-12">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="card-body">
                                            <table id="example2" class="table table-bordered table-hover">
                                                <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>PCS GROUP HEAD</th>
                                                    <th>GROUP NAME</th>
                                                    <th>CHAPEL</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for db_usered in db_usered %}
                                                    <tr>
                                                        <td>{{ db_usered.id }}</td>
                                                        <td>{{ db_usered.name }}</td>
                                                        <td>{{ db_usered.group }}</td>
                                                        <td>{{ db_usered.chapel }}&nbsp;</td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="card-footer clearfix">
{#                                            <a href="{% url 'portal:list_grouplead_url' %}"#}
{#                                               class="btn btn-sm btn-info float-left">View All Group Heads</a>#}
{#                                            <a href="{% url 'portal:add_group_url' %}"#}
{#                                               class="btn btn-sm btn-secondary float-right">New Care Group</a>#}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Pastorial Care Latest Members </h3></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                            <div class="row">
                                <div class="col-12">
                                    <div class="card">
                                        <div class="card-body">
                                            <table id="example2" class="table table-bordered table-hover">
                                                <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>LAST NAME</th>
                                                    <th>FIRST NAME</th>
                                                    <th>PHONE NUMBER</th>
                                                </tr>
                                                </thead>
                                                <tbody hx-get="{% url 'portal:lazyloadmem' %}"
                                                       hx-trigger="load">
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

templates/membersindex.html
{% for mil in mil %}
    <tr>
        <td>{{ mil.id }}</td>
        <td>{{ mil.last_name |capfirst }}</td>
        <td>{{ mil.first_name |capfirst }}</td>
        <td>{{ mil.phone_number }}&nbsp;</td>
    </tr>
{% endfor %}